name: Deploy Sanity Studio

on:
  push:
    branches:
      - main
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity Studio
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy to Sanity
        uses: sanity-io/github-action-sanity@v0.7-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        with:
          args: deploy
          
      - name: Log deployment completion
        run: echo "Sanity Studio deployed successfully at $(date)"