name: Update DataDAO Information

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update-datadaos:
    runs-on: ubuntu-latest
    environment: mainnet
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd scripts
          npm install
          
      - name: Update DataDAO information
        run: |
          cd scripts
          npm run update
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
          SUBGRAPH_URL: ${{ secrets.SUBGRAPH_URL }}
          
      - name: Log completion
        run: echo "DataDAO update completed at $(date)"